### ISSUE TITLE
Clean up teampage

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/www_threefold.tech#40]
Remove from TF Tech Business Team
- [x] Weynand Kuijpers
- [x] Adnan Fatayerji
- [x] Nickolay Babenko

Add to TF Tech Business Team
- [x] Geert Machtelinkx (see data team for info)

TF Tech Engineering Team Remove
- [x] Jo
- [x] Sarah
- [x] Others that left (please check with Nayer)

TF Tech Engineering Team Add
- [x] Whoever joined (please check with Nayer as well)

**Comment by ehab-hassan** [comment]
done at staging put there is problem with auto update ll check with support tomorrow

**Comment by VonSub** [comment]
@ehab-hassan is seems you changes for the engineering team did not go through. I still see Jo, Sarah, etc. please check again.
